Ajout de la page et de la nav
Master-Trolls-of-IT/PFEE-Front-admin pull request #1
Opened 2023-07-07 08:27 UTC by AkaMirai9

2023-07-07 12:56 UTC, Uzayur commented on .prettierrc
Pourquoi t'as pas copié celle de PLIC ?

{
    "arrowParens": "always",
    "singleQuote": true,
    "endOfLine": "crlf",
    "printWidth": 120,
    "editor.formatOnSave": true,
    "proseWrap": "always",
    "tabWidth": 4,
    "requireConfig": false,
    "useTabs": false,
    "trailingComma": "none",
    "bracketSpacing": true,
    "bracketSameLine": true,
    "jsxBracketSameLine": false,
    "semi": true
}

2023-07-07 12:56 UTC, Uzayur commented on src/index.tsx
>  // If you want to start measuring performance in your app, pass a function
C'est quoi ces coms ?

2023-07-07 12:56 UTC, Uzayur commented on src/infrastructure/controller/route/roles/anonymous-routes.tsx
> +
Oh les paths de fou

2023-07-07 12:56 UTC, Uzayur commented on src/infrastructure/controller/route/roles/common-routes.tsx
> +  // A compléter quand les composants seront créés
Mieux de mettre des TODO ici nan ?

2023-07-07 12:56 UTC, Uzayur commented on src/infrastructure/controller/theme/color.ts
> +export const MainContrastedRedColor = '#9a2c31';
On reutilise pas les wordings de plic ?

2023-09-25 18:08 UTC, lesageduvillage requested changes

2023-09-25 18:08 UTC, lesageduvillage commented on public/index.html
> +    <meta name="description" content="Web site created using create-react-app" />
go enlever ca ?

2023-09-25 18:08 UTC, lesageduvillage commented on src/infrastructure/controller/route/nav-elements.ts
> +import { CODE, DASHBOARD, QUESTION, RIGHT, TEST } from './paths';
pk en majuscule ? ca respecte pas la coding style nan ?

2023-09-25 18:08 UTC, lesageduvillage commented on src/infrastructure/controller/route/paths.ts
bizarre les majs nan ? ou c'est la norme

2023-09-25 18:08 UTC, lesageduvillage commented on src/infrastructure/controller/route/roles/anonymous-routes.tsx
> +
login_adal pas très compréhensible au passage

2023-09-25 18:08 UTC, lesageduvillage commented on src/infrastructure/controller/theme/color.ts
> +export const MainContrastedRedColor = '#9a2c31';
pk la premiere lettre est pas en minuscule d'ailleurs

2023-09-25 18:08 UTC, lesageduvillage commented on src/infrastructure/controller/store/root-store/login-store.tsx
> +class LoginStore {
t'as utilisé quoi comme logique pour le login ?

2023-09-25 18:08 UTC, lesageduvillage commented on src/infrastructure/ui/shared/icons/arrow-right-cercle.tsx
> +        d="M14.5657 6.56569C14.8781 6.25327 14.8781 5.74673 14.5657 5.43431L9.47452 0.343146C9.1621 0.0307264 8.65557 0.0307264 8.34315 0.343146C8.03073 0.655565 8.03073 1.1621 8.34315 1.47452L12.868
c'est quoi ca c'est un path ?

2023-09-25 21:48 UTC, lesageduvillage approved these changes

2023-09-25 22:00 UTC, merged