Login/logique de connexion
Master-Trolls-of-IT/PFEE-Front-admin pull request #2
Opened 2023-10-03 13:56 UTC by AymanImhah

Ajout de la logique de connexion (Hors Microsoft)

2023-10-03 14:19 UTC, lesageduvillage approved these changes
Ca me semble ok mais j'ai l'impression que t'as le meme pb que moi avec le prettier ca t'as fait changer pleins de fichiers avec une indentation différente

2023-10-03 14:20 UTC, AymanImhah commented
> Ca me semble ok mais j'ai l'impression que t'as le meme pb que moi avec le prettier ca t'as fait changer pleins de fichiers avec une indentation différente

Oui c'est pcq j'ai repris la config de PLIC front

2023-10-04 11:58 UTC, AkaMirai9 requested changes

2023-10-04 11:58 UTC, AkaMirai9 commented on src/infrastructure/controller/route/route-builder.tsx
> +    }, [SessionStore, location.pathname]);
Session store à changer avec un Store persister dans le session store

2023-10-04 11:58 UTC, AkaMirai9 commented on src/infrastructure/ui/shared/toast/notification-elements.ts
> +export const UnauthorizedAccess: NotificationCard = {
à changer par un seul objet

2023-10-04 20:25 UTC, AkaMirai9 requested changes
l'ative page

2023-10-04 20:42 UTC, AkaMirai9 approved these changes

2023-10-04 21:35 UTC, merged